### ISSUE TITLE
Configuration error during server setup

### ISSUE THREAD

**Issue by alexmigf** [syncgw/syncgw#1]
I'm encountering an error while trying to configure the server. Here's what I did:

1. Installed using Composer:

   ```shell
   composer create-project syncgw/syncgw .
   ```

2. Accessed `sync.php` on the local server.

3. Configured the server settings as follows:
   - Interface connection handler: `roundcube`
   - MySQL sync•gw database table name prefix: `syncgw`
   - Clicked "Save."

However, I'm getting the following error:

> Error loading required RoundCube configuration file '/home/alex/www/syncgw/config/config.inc.php'

I've noticed that the `config` directory is missing from my setup:

![Screenshot from 2024-10-24 17-30-12](https://github.com/user-attachments/assets/0ffc7efe-4e0e-43a4-a592-e8cca760f18b)

**Comment by syncgw** [comment]
Should be fixed with roundcube-bundle 9.20.8. 

If it does not work, please let me know.

There's a quick fix: Add `RCDirectory = "/home/alex/www/syncgw"` to `/home/alex/www/syncgw/config/syncgw.php` configuration file.

**Comment by alexmigf** [comment]
I reinstalled using the latest Roundcube version, but the issue persists.

After installation, my `RCDirectory` path was set to `"."`. I also tried the two alternative paths mentioned above, but neither resolved the problem.

As I mentioned earlier, there is no `config` directory in my setup.

**Comment by syncgw** [comment]
According to your screen shot, you did not install syncgw in RoundCube directory. There is no config direktory and all other components of RoundCube were missing. First install RoundCube (or go to the RC-directory) and then install syncgw.

**Comment by alexmigf** [comment]
Your readme mentions, "Only a web server with PHP is required to run sync•gw (no additional software or tools required)." I’ve used the composer command as instructed, but the setup then suggests configuring Roundcube. Since I only want to use WebDAV, could you confirm if this step is actually necessary?

**Comment by syncgw** [comment]
The syncgw-roundcube code is a plugin of Roundcube, so of course you need to install Roundcube first. If you use the stand-alone version, then need at least a database driver. There you can use [sync•gw mysql-bundle](https://github.com/syncgw/doc-bundle/blob/mysql-bundle/README.md) or [sync•gw file-bundle](https://github.com/syncgw/doc-bundle/blob/file-bundle/README.md). For more information about available bundles see [Available bundles](https://github.com/syncgw/doc-bundle/blob/master/Bundles.md).
